#必须，无需更改
server: 
  port: 8080

#必须
#根据不同环境设置各环境的eureka server的url
eureka: 
  instance: 
    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10 #prod建议删除该配置
#    leaseExpirationDurationInSeconds: 30 #prod建议删除该配置
  client: 
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://Juran-Alpha-1a-eureka-server-Ubt-1:8080/eureka/,http://Juran-Alpha-1a-eureka-server-Ubt-2:8080/eureka/,http://Juran-Alpha-1a-eureka-server-Ubt-3:8080/eureka/

#exampleuser-app: 
#  feign: 
#    url: 54.223.123.229:8080

#必须，无需更改
feign: 
  hystrix: 
    enabled: true

#必须，无需更改    
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 3000

#必须
#修改 spring.application.name
#修改 spring.jersey.jaxrsApplicationClass
spring: 
  application: 
    name: examplemovie-app
  http: 
    encoding: 
      charset: UTF-8
      force: true
      forceRequest: true
      forceResponse: true
  jersey: 
    enabled: true
    urlMappings: /api/*
    jaxrsApplicationClass: com.juran.examplemovie.app.config.RestJerseyRegister

#必须，无需更改  
logging:  
  config: classpath:log4j2.xml

#必须，无需更改    
eventlog: 
  component: 设计家平台
  subSystem: ${spring.application.name}
  framework: J2EE+SpringCloud

#必须
#PROD环境及UAT环境需将springfox.config.enabled设为false
#修改springfox.config.resourcePackage  
#修改title、contact等信息为自己的
#访问地址：http:xxx:8080/swagger-ui.html
springfox: 
  config:
    enabled: true
    configId: examplemovie-swagger2-jersey2
    title:  脚手架电影服务-REST服务接口列表
    version:  1.0.0
    contact: 暂无联系人
    schemes: http,https
    basePath: /api
    resourcePackage: com.juran.examplemovie.app.resource
    prettyPrint: true
    scan: true
  documentation: 
    swagger: 
      v2: 
        path: /api/swagger.json #/v2/api-docs

#必须
#修改为自己的数据库地址 
#根据不同环境修改为各环境的数据库地址       
mysql:  
  standalone: 
    enabled: false
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.199.38.147:3306/mdm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql
    maxActive: 100
    initialSize: 10
  readWrite: 
    enabled: true
    write:    
      - driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://leedian-ezhome-qa-rds-mysql.cfyuzargym1l.rds.cn-north-1.amazonaws.com.cn:3306/example_movie?useUnicode=true&characterEncoding=utf-8
        username: dba
        password: LeedianRDSMySQLDBA
        maxActive: 100
        initialSize: 10  
    read: 
      - driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://leedian-ezhome-qa-rds-mysql.cfyuzargym1l.rds.cn-north-1.amazonaws.com.cn:3306/example_movie?useUnicode=true&characterEncoding=utf-8
        username: dba
        password: LeedianRDSMySQLDBA
        maxActive: 100
        initialSize: 10  

#必须
#修改mapperLocations、typeAliasesPackage
mybatis: 
  datasource: 
    enabled: true
    mapperLocations: classpath:com/juran/examplemovie/app/dao/xml/*.xml
    typeAliasesPackage: com.juran.examplemovie.app.dao.bean
  pagehelper: 
    enabled: true
    offsetAsPageNum: true  #默认为false，为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用
    rowBoundsWithCount: false #默认为false，为true时，使用 RowBounds 分页会进行 count 查询。
    pageSizeZero: false #默认为false，为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
    reasonable: false  #默认为false，为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: false #默认值false，支持通过 Mapper 接口参数来传递分页参数，自动根据上面 params 配置的字段中取值
    dialect: #自定义分页逻辑需要设置这个值为分页的类
    helperDialect: mysql  #配置分页对应的数据库
    autoRuntimeDialect: false #默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
    autoDialect: 
    closeConn: true #默认值为 true。当使用运行时动态数据源或没有设置 helperDialect 属性自动获取数据库类型时，会自动获取一个数据库连接， 通过该属性来设置是否关闭获取的这个连接
    params: count=countSql  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射
  

#选择
mongodb: 
  base: 
    enabled: false
    hostPort: 10.199.138.199:8080,10.199.138.200:8080   
    database: xxx
    userName: xxx
    passWord: xxx
    connectTimeout: 2000 #获取链接超时
    socketTimeout: 3000  #IO超时
    serverSelectionTimeout: 3000 #等待应用程序超时
    
solr: 
  base: 
    urls: http://54.222.214.86:8080/solr/cas